# Generated by Django 2.1.3 on 2018-12-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(default='익명', max_length=150),
        ),
    ]
