# Generated by Django 2.1.3 on 2018-12-08 12:53

from django.db import migrations, models
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=market.models.get_image_path),
        ),
    ]
