# Generated by Django 2.1.3 on 2018-12-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20181209_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='stars',
            field=models.PositiveIntegerField(default=0, verbose_name='총 별점'),
        ),
    ]
