# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.PositiveSmallIntegerField(choices=[(0, '장소'), (1, '분위기')], verbose_name='태그 타입')),
                ('tag', models.CharField(max_length=10, verbose_name='태그')),
            ],
        ),
    ]
