# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 08:34
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_idx', models.PositiveIntegerField(blank=True, null=True, verbose_name='회원정보_idx')),
                ('contracts', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('member_type', models.PositiveSmallIntegerField(choices=[(0, '소비자'), (1, '사진작가')], verbose_name='회원종류')),
                ('consumer_idx', models.PositiveIntegerField(blank=True, null=True, verbose_name='소비자_idx')),
                ('photographer_idx', models.PositiveIntegerField(blank=True, null=True, verbose_name='사진작가_idx')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markets', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('member_idx', models.PositiveIntegerField(blank=True, null=True, verbose_name='회원정보_idx')),
            ],
        ),
    ]
